### ISSUE TITLE
Batches of random variables

### ISSUE THREAD

**Issue by pnkraemer** [probabilistic-numerics/probnum#388] opened 2021-04-28 16:16 UTC
As discussed offline a few weeks ago, the `RandomVariable` implementation would benefit from allowing batches.

A batch would be a collection of independent random variables of a common type, for instance a batch of multivariate Normal distributions. Currently, this case is handled in `_RandomVariableList`, which was intended as a temporary solution (hence the underscore).
Having such a batch of, e.g., Normals would allow storing mean and covariance efficiently, which in turn will speed up a lot of computation that uses lists of Normal objects (currently, this is used heavily in e.g. `KalmanPosterior` objects -- sampling for instance would be so much faster!).

A solution would be that each random variable has both, a `batch_shape` and an `event_shape`. This is how Tensorflow Probability handles it (https://github.com/tensorflow/probability/blob/master/tensorflow_probability/examples/jupyter_notebooks/Understanding_TensorFlow_Distributions_Shapes.ipynb).

Perhaps it would be a good idea to change for instance `.reshape()` into `.batch_reshape` and `.event_reshape()`. 
What I am a little bit worried about is implementing random variable arithmetic and broadcasting. Would that even be possible/recommended? What would broadcasting even refer to? A batch-broadcast, an event-broadcast, or a batch-and-event-broadcast?

**Comment by JonathanWenger** [comment] 2021-06-22 12:12
This is a duplicate of #428

**Closed by JonathanWenger** 2021-06-22 12:12 UTC
Labels: duplicate, feature request, prob, refactoring
